import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import "../../../firebase.config";
import StoreProvider from "../providers/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  locale: never;
}

export default function RootLayout({ children, locale }: RootLayoutProps) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <StoreProvider>
          <div className="p-4">{children}</div>
        </StoreProvider>
      </body>
    </html>
  );
}
